
package com.wury.soap.client.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloJavaImplService", targetNamespace = "http://endpointImpl.soap.wury.com/", wsdlLocation = "http://localhost:9999/ws/hello?wsdl")
public class HelloJavaImplService
    extends Service
{

    private final static URL HELLOJAVAIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOJAVAIMPLSERVICE_EXCEPTION;
    private final static QName HELLOJAVAIMPLSERVICE_QNAME = new QName("http://endpointImpl.soap.wury.com/", "HelloJavaImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOJAVAIMPLSERVICE_WSDL_LOCATION = url;
        HELLOJAVAIMPLSERVICE_EXCEPTION = e;
    }

    public HelloJavaImplService() {
        super(__getWsdlLocation(), HELLOJAVAIMPLSERVICE_QNAME);
    }

    public HelloJavaImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOJAVAIMPLSERVICE_QNAME, features);
    }

    public HelloJavaImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOJAVAIMPLSERVICE_QNAME);
    }

    public HelloJavaImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOJAVAIMPLSERVICE_QNAME, features);
    }

    public HelloJavaImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloJavaImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloJava
     */
    @WebEndpoint(name = "HelloJavaImplPort")
    public HelloJava getHelloJavaImplPort() {
        return super.getPort(new QName("http://endpointImpl.soap.wury.com/", "HelloJavaImplPort"), HelloJava.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloJava
     */
    @WebEndpoint(name = "HelloJavaImplPort")
    public HelloJava getHelloJavaImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpointImpl.soap.wury.com/", "HelloJavaImplPort"), HelloJava.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOJAVAIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOJAVAIMPLSERVICE_EXCEPTION;
        }
        return HELLOJAVAIMPLSERVICE_WSDL_LOCATION;
    }

}
